### ISSUE TITLE
Unsoundness in `type_of_sum` returning a product, not sum type

### ISSUE THREAD

**Issue by Centril** [clockworklabs/SpacetimeDB#104]
See https://github.com/clockworklabs/SpacetimeDB/blob/c3526ee61db444b7af850a0ad870352fd045425f/crates/sats/src/algebraic_value.rs#L373-L386.

**Comment by marvin-hansen** [comment]
Does SATN actually support recursive types?
 I don't remember having seen it in the docs.

**Comment by cloutiertyler** [comment]
> Does SATN actually support recursive types? I don't remember having seen it in the docs.

It does, yes.
