### ISSUE TITLE
Websockets - Don't compress small messages

### ISSUE THREAD

**Issue by Centril** [clockworklabs/SpacetimeDB#1080]
A recent profile of a large scale workload showed that brotli compression accounts for nearly 15% of total work

<img width="1413" alt="Screenshot 2024-04-11 at 5 36 47 PM" src="https://github.com/clockworklabs/SpacetimeDB/assets/141075564/30a62ef8-c6fc-4c86-9a4f-fc43c2f27c3d">

This is due to the fact that we compress all outgoing websocket messages. However, the vast majority of messages are `TransactionUpdates` which are too small to benefit from compression. Instead we should compress messages based on either their size or their type, since in most cases it is only beneficial for `SubscriptionUpdates` and ad hoc queries.

**Comment by bfops** [comment]
We might also want to investigate switching Brotli for a compression algorithm more designed to be fast and stream-supporting (e.g. I think maybe LZ4?)

**Comment by cloutiertyler** [comment]
We should investigate gz as well because this is as available as brotli

**Comment by PuruVJ** [comment]
I'm not too keen on LZ4, it doesn't have a built-in way in web, so we'll just be swapping out 90kb of brotli for a similar number of kbs for lz4 library. Notably, the web version of lz4 was last maintained 6 years ago https://github.com/Benzinga/lz4js

I'd advocate going with gzip, its built-in web, so thats essentially 0 bytes

**Comment by bfops** [comment]
It sounds like @Centril has already done this?
