### ISSUE TITLE
The caller of a reducer call should always receive the result even if they’re not subscribed to any of the tables that have changed

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#1127]
John Dec 11th: We've talked about this issue many times, I'll test to see if we actually implemented this or not.

Piotr: as far as I've checked it doesn't work yet, so I'll look into it

**Comment by drogus** [comment]
PR: https://github.com/clockworklabs/SpacetimeDB/pull/1111/files

**Comment by cloutiertyler** [comment]
The caller should receive an event with no rows if they are not subscribed to any of the rows that have changed.

**Comment by cloutiertyler** [comment]
@gefjon to add an SDK test before merging

**Comment by gefjon** [comment]
> @gefjon to add an SDK test before merging

Done!
