### ISSUE TITLE
Add request context to datastore traits

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#1144]
Currently, once a transaction has started, it will run till completion. There is no way to stop its execution. The datastore traits need some sort of request context that can be polled periodically such that a transaction can be stopped prematurely in the case that the originating connection is closed, the originating request times out, etc.

**Comment by cloutiertyler** [comment]
I propose that we close this one given that we've closed the query timeout one in favor of the energy estimation approach
