### ISSUE TITLE
Store table row size in system table

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#1161]
Ideally this would be a column in `st_table`, but I don't think we want to change the schema of `st_table`. It could also be a view over `st_columns`, but in that case we'd need to add an index to `st_columns`. The fastest, in terms of deriving the row size, is probably just to store it in a new system table. Perhaps the same one as https://github.com/clockworklabs/SpacetimeDB/issues/1158.

**Comment by Shubham8287** [comment]
Should we have `ST_STATS` for storing  row size, row count, etc about a table?

**Comment by joshua-spacetime** [comment]
> NOTE: This is presumably only the fixed len portion of the row?

Correct, specifically the BFLATN size.

> Should we have ST_STATS for storing row size, row count, etc about a table?

Yes I think so.

**Comment by egormanga** [comment]
Is there any documentation on how to query for table row size? My case requires me to estimate storage & memory usage growth.
