### ISSUE TITLE
CLI Bug: If a server has no default identity, calling spacetime publish will create + add a new identity for that server

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1182]
This issue may be aggrivated by having the server's keys rotated. See the discussion here: https://github.com/clockworklabs/SpacetimeDB/pull/1109

John 4/22/2024: I tested this locally and I was not able to get my local CLI into the bugged state.

**Comment by gefjon** [comment]
What is the expected / desired behavior here?

**Comment by cloutiertyler** [comment]
Closing because we don't really remember the context and it's not clear what the desired behavior is.
