### ISSUE TITLE
`SELECT * FROM *` no longer allowed in subscriptions

### ISSUE THREAD

**Issue by gefjon** [clockworklabs/SpacetimeDB#1199]
Errors with `Unsupported query on subscription: "Multiple statements in subscription query"`.

Should also add a test to the SDK tests which exercises this.

**Comment by gefjon** [comment]
Likely the path of least resistance here is, instead of recognizing `SELECT * FROM *` in the SQL compiler, detecting it earlier when parsing the `Subscribe` message and invoking a separate compilation path.

**Comment by joshua-spacetime** [comment]
I know we need to support this for the time being, but we should probably reconsider whether we want to support it for 1.0. It's a useful utility, but technically it's not valid SQL.

**Comment by gefjon** [comment]
I added a test for this to the branch `phoebe/select-star-broken`, but am now going to do by very best to find someone who isn't me to fix it.

**Comment by jdetter** [comment]
We *need* to support this feature, but in terms of what the specific syntax is or how its implemented doesn't matter to me.
