### ISSUE TITLE
Implement consistent filtering rules proposal

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1256]
Progress:

- [x] Rust client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1275
- [x] C# client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1277 + https://github.com/clockworklabs/spacetimedb-csharp-sdk/pull/93
- [x] TypeScript client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1276
- [x] Rust server-side: https://github.com/clockworklabs/SpacetimeDB/pull/1280
- [x] C# server-side: https://github.com/clockworklabs/SpacetimeDB/pull/1282

**Comment by RReverser** [comment]
Progress:

- Rust client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1275
- C# client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1277 + https://github.com/clockworklabs/spacetimedb-csharp-sdk/pull/93
- TypeScript client-side: https://github.com/clockworklabs/SpacetimeDB/pull/1276
- Rust server-side: TODO
- C# server-side: TODO
