### ISSUE TITLE
Client subscription permissions

### ISSUE THREAD

**Issue by puddleglum56** [clockworklabs/SpacetimeDB#1323]
Hello! I was looking through the [SpacetimeDB tutorial in the documentation](https://spacetimedb.com/docs/unity/part-3) and thinking about how I could implement SpacetimeDB in my game. I was wondering if there is any way to limit clients' visibility to certain rows/tables on the server side, since I can't trust my clients and I don't want them to be able to see things they shouldn't. From my understanding, currently any client can subscribe to any change in any row in any table. Is that true? Or is there some logic that handles permissions based on Identity of the subscriber?

**Comment by puddleglum56** [comment]
Hi Mazdak, thanks for your reply! Currently, users can belong to a group
indicated by an indexed column in the Users table. Users should only be
notified of certain events if they are within a group for that event. I
might need to restructure my tables to be more in line with ECS to be more
compatible with SpacetimeDB, maybe that’s where I’m going wrong.

**Comment by gefjon** [comment]
The feature you're interested in is called "row-level permissions." We've been actively doing design work for the past several weeks. We hope to have something to show you soon, but be aware that this is a complicated feature with major security and performance implications, and we want to take the time to get it right.

**Comment by puddleglum56** [comment]
Hi, sounds good! I’ll close the issue and keep an eye out for those features.

**Comment by Flavelius** [comment]
I'm interested in this as well for similar reasons. Has it been addressed in the meantime?
Allowing clients to control subscriptions / data access seems like a design issue to me.
I would expect clients to only be allowed to make requests and the server to manage subscriptions in response.

**Comment by willstott101** [comment]
I can't find anything in the docs but: https://github.com/clockworklabs/SpacetimeDB/blob/aac7894aacf081f4d4638145f58a35ae68ebe898/smoketests/tests/rls.py#L13 I might see if I can get this to work...
