### ISSUE TITLE
C# bindings for scheduled tables

### ISSUE THREAD

**Issue by Shubham8287** [clockworklabs/SpacetimeDB#1327]
look at corresponding rust binding ticket - https://github.com/clockworklabs/SpacetimeDB/issues/1326.

modify `spacetimedb(table)` macro for  `scheduled` argument as described here - https://github.com/clockworklabs/SpacetimeDBPrivate/blob/shub/timers-proposal/proposals/0005-timers.md#api-design

**Comment by RReverser** [comment]
I'll get around to implementing this after the refactoring I'm currently working on, but meanwhile @Shubham8287 would it be possible to extend the spec with proposed API for C#? (you can take a look at C# module reference docs for how it works now)

I'm happy to implement it, but if you could spec out the design, that would be most helpful.

Going forward, perhaps we should always declare design for all languages in proposals, e.g. like I did in the Consistent Filtering proposal.

**Comment by bfops** [comment]
I believe this is done (in https://github.com/clockworklabs/SpacetimeDB/pull/1449)
