### ISSUE TITLE
(latest master) Issue with config lock file

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/SpacetimeDB#1339]
I keep hitting this on macos when trying to publish BitCraft, I have a feeling the BitCraft team will run into this as well. The problem resolves if I delete the lock file but then it comes back.

```
(python-env) boppy@macbook game % spacetime publish -c bitcraft -s local -S
thread 'main' panicked at crates/cli/src/config.rs:911:58:
called `Result::unwrap()` on an `Err` value: Unable to acquire lock on config file "/Users/boppy/.spacetime/config.toml": failed to create lockfile "/Users/boppy/.spacetime/config.lock"

Caused by:
    File exists (os error 17)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jdetter** [comment]
FWIW I also was running into this on windows a while ago so its probably present there as well

**Comment by bfops** [comment]
I was able to reproduce this by killing a `spacetime publish` (with `Ctrl-C`).

Notably, `spacetime publish` holds the lock for the entire duration, which includes compiling and crossing a network.
