### ISSUE TITLE
[STABILITY] API design: find_by_{} vs filter_by_{} for unique columns

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1365]
As discussed, this is an API design question that we need to answer at least before 1.0.

Right now Rust calls two kinds of methods `filter_by_{}`: one for unique columns, which returns an Option, and another for non-unique columns which returns an iterator.

While Option is iterable , a lot of methods don’t overlap: e.g. if user is doing `table.filter_by_x().collect()` and later down the road adds unique constraint to `x`, our current design will cause such callsites that already use `filter_by_x()` as regular iterator, to fail to compile, because they’re now returning a different type than user expected. In C# naming both the same way would be even less ideal, because optional values are represented via nullable and there is no overlap between usages of `T?` and `IEnumerable<T>` so even more code would have to be updated. This seems not ideal and causes issues similar to ones in weakly typed languages.

Instead it seems like a less surprising behaviour to ensure that same-named methods always return same expected type - in this case, an iterator. So for all columns regardless of their attribute we’ll have `filter_by_{}` that always returns an iterator, and for unique ones we’ll generate a `find_by_{}` method that returns an Option. This way generic filtering code that just wants to show found results and doesn’t care about unique constraint will continue to work via `filter_by_{}` as expected, and code that really cares about there being only one or zero values will be able to use `find_by_{}`.

This will also make API more consistent with Rust’s own Iterator which uses `find` with predicate to return an Option and `filter` to return another Iterator.

If we do this change it probably needs to be done at least before we commit to a stable API in 1.0.

**Comment by cloutiertyler** [comment]
@RReverser this is done, right?

**Comment by RReverser** [comment]
Yes.
