### ISSUE TITLE
C# SDK test suite

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1376]

**Comment by RReverser** [comment]
I added tests to the C# client SDK over the weekend.

They're snapshot-based tests that use the quickstart example as a demo, with pre-recorded chat session between 2 participants, and verify that all the reducer events, table events, log messages, final table contents and stats behave as expected in future changes.

They can definitely be extended further (e.g. to cover more types) in the future, but I think that can be done as a separate improvement outside this issue.
