### ISSUE TITLE
Inherent method for `::delete` should be generated for TableTypes

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1386]

**Comment by gefjon** [comment]
Unassigning myself because I have too many 0.12 tickets.

**Comment by cloutiertyler** [comment]
@gefjon I'm readding you here because this one is relevant to the API stability proposal and I'm going to move you off of some other tickets.

**Comment by gefjon** [comment]
My proposal as it is now supersedes this ticket; this is no longer meaningful in the world where we do not impose a 1-to-1 equivalence between tables and types. Will leave this open in case the proposal changes significantly, but currently I expect to close this issue as stale within the 0.12 window.
