### ISSUE TITLE
If you connect to SpacetimeDB with an invalid token in Unity it says "Connection error Unable to connect to remote server". This should be changed to tell you your token is bad.

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1397]
### zeke investigation results so far
- BitCraft has started handling this error better
- The Unity SDK is just passing along the `WebSocketException`, which is not a type we construct (in the SDK)
- The websocket error code is set to `Success`
- Next steps: Investigate what sets these error details on the server side

**Comment by cloutiertyler** [comment]
The error response message from SpacetimeDB needs to differentiate between connecting to a module that doesn't exist and a bad token. We do not currently do this. This is an API break.

**Comment by cloutiertyler** [comment]
We just need to update this so that clients receive an error message that their connection is bad.

**Comment by bfops** [comment]
It's worth saying that we're planning to rework identities & tokens pretty soon - maybe we should revisit this after that refactoring happens?

**Comment by cloutiertyler** [comment]
I'll just note, that in a meeting with @jdetter we decided that the identities and tokens rework is not going to make this issue go away although hopefully it will make it less frequent.

**Comment by gefjon** [comment]
Empirical analysis shows this to be the SDK's problem, not the host's. The host sends a reasonable HTTP error response with a well-chosen status code and a human-readable description in the body in response to `/database/subscribe` calls with invalid tokens, and the Rust SDK is able to print these. (Currently it prints the status code but not the body, but it clearly receives the intended response.) Somewhere in the C# SDK, whether it's our code or the WebSocket library we use, the client is discarding that HTTP error response and printing something stupid and useless instead.

**Comment by cloutiertyler** [comment]
We have determined that this is an issue in the C# SDK or C# websocket client specifically. It is correct in the API. Thus I'm moving this to 1.0.

**Comment by joshua-spacetime** [comment]
Fixed by https://github.com/clockworklabs/com.clockworklabs.spacetimedbsdk/pull/166
