### ISSUE TITLE
Request for a security contact

### ISSUE THREAD

**Issue by RedYetiDev** [clockworklabs/SpacetimeDB#1410]
Hi! I'm a security researcher, and I believe I have identified a vulnerability within this software, if possible could I have a security contact?

**Comment by gefjon** [comment]
You can reach out to us at contact@spacetimedb.com , or find us on Discord at https://discord.com/invite/SpacetimeDB .

**Comment by RedYetiDev** [comment]
Thanks! I’ll send my report there!
