### ISSUE TITLE
User generated types shouldn’t conflict with SpacetimeDB types, e.g. Message

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1428]
#[spacetimedb(table)]
pub struct Message {
   ...
}

**Comment by cloutiertyler** [comment]
What is the proposed solution for this one @RReverser? A compiler error + a runtime error if you work around the compiler error?

**Comment by RReverser** [comment]
I think that's the issue I originally reported? My idea back then was just to change default namespace of `spacetime generate` to non-SpacetimeDB one. That would be enough to ensure that user types don't conflict with ours.

**Comment by cloutiertyler** [comment]
@RReverser Is this now fixed in the C# SDK?

@gefjon is this an issue in the Rust SDK?

**Comment by cloutiertyler** [comment]
@gefjon has confirmed this is not an issue in the Rust SDK.

**Comment by cloutiertyler** [comment]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/c7176375-7511-4812-8948-39441c303527">
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/a2041ab2-276f-4d6b-b91c-2ef7e298e545">

**Comment by RReverser** [comment]
Looking deeper at the history, it seems this was fixed a while back in https://github.com/clockworklabs/SpacetimeDB/pull/88. Before that change, types were generated in the `SpacetimeDB` namespace, conflicting with built-ins, but nowadays they're generated in `SpacetimeDB.Types`, so this is no longer an issue.
