### ISSUE TITLE
Don't generate client bindings for private tables

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1431]

**Comment by cloutiertyler** [comment]
I did not create this ticket, and I am wondering if we truly don't want to do this.

**Comment by cloutiertyler** [comment]
@kazimuth I am assigning this to you. You need to decide if this is something we want to do in the context of whether clients should break or not when changing public/private table designation.

Personally I think a public/private change should not break clients (except if they rely on the actual row data of course).

**Comment by jdetter** [comment]
If we have these tables:
```rust
#[spacetimedb(table(private))]
pub struct Player {
    #[primarykey]
    identity: Identity,
    #[unique]
    #[autoinc]
    player_id: u32,
    name: String,
}

#[spacetimedb(table(public))]
pub struct LoggedOutPlayer {
    #[primarykey]
    identity: Identity,
    player: Player, // References a private table type
}
```

If we're doing this correctly, we *should* codegen both types (Player and LoggedOutPlayer) but then only do codegen for the LoggedOutPlayer table, not for the Player table.

**Comment by joshua-spacetime** [comment]
Closing since we won't be adding support for this in 1.0.
