### ISSUE TITLE
Don't report private tables in module description

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1432]
Phoebe: This needs some design work - likely the owner should see private tables, but anonymous or other identities should not.

**Comment by cloutiertyler** [comment]
I did not create this ticket, and I don't know that we want to not do this.

**Comment by cloutiertyler** [comment]
@kazimuth I am also assigning this one to you. I don't believe that we should do this, but it bears some discussion on migrations and compatibility.

**Comment by joshua-spacetime** [comment]
Closing since we won't be supporting this in 1.0.
