### ISSUE TITLE
CLI: Refactor and reuse `Arg` parsers to ensure consistent UX

### ISSUE THREAD

**Issue by Centril** [clockworklabs/SpacetimeDB#1451]
Currently, parsers for e.g., `--identity` and friends are copy-pasted across our CLI code.
It would be good to deduplicate these so that:
1. we cut down on code, which is good for readability and bug reduction.
2. we ensure a consistent UX in terms of flags, types, help messages, etc. This way, we avoid subtle differences.

**Comment by bfops** [comment]
I did a pass on this a while ago - I think it's in a better state now (see `common_args.rs`). feel free to reopen if there are still copy-pasted things that you think we should factor together.
