### ISSUE TITLE
Fix: Smoketests failing in `master`

### ISSUE THREAD

**Issue by bfops** [clockworklabs/SpacetimeDB#1471]
Smoketests have started [failing](https://github.com/clockworklabs/SpacetimeDB/actions/runs/9749442459/job/26906593084) in SpacetimeDB `master`, despite no code changes. Maybe due to spacetimedb-csharp-sdk changes?

## Definition of Done
SpacetimeDB smoketests are passing again

**Comment by Shubham8287** [comment]
Initially I got deviated via some other smoketest failures - https://github.com/clockworklabs/SpacetimeDB/actions/runs/9570258605/job/26909191811#step:6:1972, It looks these are the test get skip for most of the time but ran for some reason on this instance.

Anyway, error to break the master CI is this one - https://github.com/clockworklabs/SpacetimeDB/actions/runs/9570258605/job/26909191811#step:6:1972, which does not appears to be a sdk error rather related codegen here - https://github.com/clockworklabs/SpacetimeDB/pull/1312/files#diff-309e3a7a386f6ef6ad03b1abec60548bb53a35855d452a6df5d1e0c954e18db4R26


To reproduce -
1. `spacetime init --lang csharp`
2. `spacetime build` 

To fix locally (Can't say if this is the right way) - Add `      <PackageReference Include="SpacetimeDB.Codegen" Version="0.10.*" />` to `StdbModule.csproj` `ItemGroup` this will let the module build

**Comment by bfops** [comment]
Ah, the C# NuGet packages were updated in recent versions of SpacetimeDB: https://github.com/clockworklabs/SpacetimeDB/pull/1440, but those updated packages have not yet been published. Presumably it will work once the packages are published as 0.11.

**Comment by bfops** [comment]
We should probably revert the codegen changes until we have published a functioning version of these packages, _or_ figure out how to locally override something so that `dotnet` looks for these packages on the local machine rather than in NuGet. @jdetter do you have thoughts?

**Comment by Shubham8287** [comment]
Oh lol, you had all the missing context. Cool!

**Comment by bfops** [comment]
Further thoughts: maybe the NuGet packages should be in a different repo altogether? This is sort of evidence that the NuGet package updates shouldn't immediately be incorporated into SpacetimeDB until they're actually published.

And/or we should consider setting up an alternate package source (e.g. local disk) for SpacetimeDB devs, so that we can immediately update SpacetimeDB code to use "bleeding edge" versions of the NuGet packages, without having to publish those packages to "official" NuGet.
