### ISSUE TITLE
Python link in the README is broken

### ISSUE THREAD

**Issue by LiamSwayne** [clockworklabs/SpacetimeDB#1554]
The link to the Python client-side library is a 404

https://spacetimedb.com/docs/sdks/python/quickstart

**Comment by cloutiertyler** [comment]
@LiamSwayne Thanks for the heads up. We actually decided to remove official Python support until after the 1.0 release since it was too many languages for us to manage while many APIs were changing.

Here is the unmaintained Python SDK: https://github.com/clockworklabs/spacetimedb-python-sdk
