### ISSUE TITLE
CLI - Error in command caused deletion of entire config.toml

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1581]
```
spacetime sql control-database "SELECT * FROM Node"
config file "/Users/tylercloutier/.spacetime/config.toml" is invalid: Error {
    inner: Error {
        inner: TomlError {
            message: "duplicate key `identity` in table `identity_configs`",
            original: Some(REDACTED BY TYLER BUT THIS WAS THE CONTENT OF THE FILE),
            keys: [],
            span: Some(
                3092..3093,
            ),
        },
    },
}
Error: Cannot find protocol for default server

Caused by:
    No default server configuration.
    Set an existing server as the default with:
    	spacetime server set-default <server>
    Or add a new server which will become the default:
    	spacetime server add <url> --default
```

After this error the config.toml file was just empty.

**Comment by bfops** [comment]
Context: This happened after a manual edit to the `config.toml`, which caused the CLI to treat the config as malformed due the duplicate identities mentioned in the error message.

Our CLI generally doesn't handle kindly any errors in the config file.

We discussed and we're assigning this to me to do a bit of research and propose something a little less jarring for users.

(Also, for the record, @gefjon points out correctly that as long as our CLI doesn't handle these cases well, we should really really discourage users from making any manual edits).

**Comment by bfops** [comment]
in the immediate term, since this might be easier than training users, we should probably do one of:
- not overwrite the config file if it fails to parse
- tell the user that we can't load their config, and prompt if they want to overwrite
- before we save the config file, copy the existing file to config.toml.bak

**Comment by gefjon** [comment]
If we're going to allow or encourage users to edit their config files by hand, we should also look into preserving comments and formatting.
