### ISSUE TITLE
RLS: Store module defined RLS queries in system table

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#1600]
This ticket includes (1) creating a system table for RLS queries, and (2) updating the drivers of `__describe_module__` (database init and update) to insert RLS queries into this system table.

Note, the module should fail to compile if the queries fail to compile.

**Comment by mamcx** [comment]
The pr for this ticket doesn't check the validity of the query, only adds the table. It will done for #1602
