### ISSUE TITLE
Docker image is arm64 - only seems to work on M1

### ISSUE THREAD

**Issue by configurator** [clockworklabs/SpacetimeDB#168]
I was trying to run spacetimedb on Docker in a default GitHub Codespace, and apparently the image is only built for arm64. To work on intel CPUs, the image needs to be multi-arch on Dockerhub.

```
$ docker run --name spacetimedb clockworklabs/spacetimedb:latest start
Unable to find image 'clockworklabs/spacetimedb:latest' locally
latest: Pulling from clockworklabs/spacetimedb
fc9ce7290e7e: Pull complete 
be081aa8c78b: Pull complete 
3ee2becf8478: Pull complete 
Digest: sha256:3415fd15cdcbc25e36ee0ca4c9a7dd0af949629a3fb18818885e275e844427f6
Status: Downloaded newer image for clockworklabs/spacetimedb:latest
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested

$ docker logs spacetimedb
exec /usr/local/bin/spacetimedb: exec format error
```

**Comment by cloutiertyler** [comment]
Thanks for the heads up! We added this last minute so, it's definitely possible. @jdetter Can you look into this?

**Comment by kim** [comment]
It seems like `latest` is actually outdated (and not multi-arch). Meanwhile you could try `clockworklabs/spacetimedb:branch-master`.

**Comment by jdetter** [comment]
FWIW its actually broken on all platforms except M1 mac right now, I'm working on fixing this.

**Comment by drogus** [comment]
Sorry for no response earlier. This was fixed in the last few days and now the `latest` version (as well as the `master` branch build etc) should be working on both `arm64` and `amd64` archs. Please let us know in case of any other problems!
