### ISSUE TITLE
Fix hotswapping modules (No longer working in 0.12)

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1807]

**Comment by bfops** [comment]
I will try to repro this

**Comment by bfops** [comment]
A minimal test of hotswapping has worked for me:
1. `spacetime init --lang rust my_new_project`
2. `spacetime publish -s local test-project`
3. Run in another terminal: `spacetime subscribe -s local test-project 'select * from person'`
4. `spacetime call -s local test-project add Person1`
5. Change a log message -> `spacetime publish -s local test-project`
6. `spacetime call -s local test-project add Person2`
7. Observe the log message from before and after the hotswap via `spacetime logs -s local test-project`
8. Observe that the `subscribe` saw both rows

**Comment by bfops** [comment]
Reassigning to keep investigating. We have a repro using https://github.com/clockworklabs/SpacetimeDBCircleGame/pull/2; specifically, by switching the food count and trying to re-publish the module.. but it's unclear why it's failing, and attempting a more minimal repro does not work.

**Comment by bfops** [comment]
This is the smallest repro I could come up with.

Module code:
```rust
use spacetimedb::{ReducerContext, SpacetimeType, Table};

#[spacetimedb::table(name = entity, public)]
pub struct Entity {
    pub position: Vector2,
}

#[derive(SpacetimeType, Debug, Clone, Copy)]
pub struct Vector2 {
    pub x: f32,
    pub y: f32,
}

#[spacetimedb::reducer]
pub fn spawn_food(ctx: &ReducerContext) -> Result<(), String> {
    let count = ctx.db.entity().count();
    if count < 600 as u64 {
        ctx.db.entity().try_insert(Entity {
            position: Vector2 { x: 0.0, y: 0.0 },
        })?;
    }
    Ok(())
}
```

And repro process:
```bash
echo "Publishing.."
spacetime publish -s local circle-test --delete-data --yes

echo "Updating count.."
sed -i'' -e 's/\<600\>/6000/' src/lib.rs

echo "Republishing.."
if spacetime publish -s local circle-test --build-options="--skip-println-checks"; then
  echo "---- THIS DID NOT FAIL!!!!! ----"
fi

echo "Reverting count.."
sed -i'' -e 's/\<6000\>/600/' src/lib.rs
```

**Comment by cloutiertyler** [comment]
This ended up being a schema issue which is fixed now in: https://github.com/clockworklabs/SpacetimeDB/pull/1813
