### ISSUE TITLE
Mac: Brew install fails with SHA256 mismatch

### ISSUE THREAD

**Issue by marvin-hansen** [clockworklabs/SpacetimeDB#184]
On M1 Mac with Ventura (13.4)

brew install clockworklabs/tap/spacetime

Results in:

Error: spacetime: SHA256 mismatch
Expected: 64534d142f6618c7bb6be9a0b19f7b7185069cb842afa0df086d1e2fcf7e7f29
  Actual: 40c553be7246d709a08ccf07a20e73db2503127853c256b3de9fff4a95062db2

Looks like somehow the binary was updated without updating the hash.

Any idea?

**Comment by cctrz** [comment]
you can do a temp fix by doing 
`brew edit clockworklabs/tap/spacetime`

and change the hash in this part:
```
if Hardware::CPU.arm?
  url "https://github.com/clockworklabs/SpacetimeDB/releases/latest/download/spacetime.darwin-arm64.tar.gz"
  sha256 "40c553be7246d709a08ccf07a20e73db2503127853c256b3de9fff4a95062db2"
```

**Comment by cloutiertyler** [comment]
@cctrz @marvin-hansen Thanks for the heads up! This should be fixed now!
