### ISSUE TITLE
Implement `spacetime login`

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#1847]
Steps:

1.  The CLI starts a websocket connection to `https://spacetimedb.com/login-cli`
2. It passes in a random nonce that it created to the websocket
3. Zeke figures out how to open the default browser and set the url to be `https://spacetimedb.com/login-cli?nonce={the nonce}`
4. The user logs in on the browser
5. The API backend sends the session token to the CLI over the websocket connection
6. The CLI provides the session token on every subsequent request to the website API
7. The CLI hits the `/v1/identity` endpoint to receive a SpacetimeDB token
8. The CLI provides this token to all SpacetimeDB requests (unless they are flagged `--anonymous`.

**Comment by bfops** [comment]
ChatGPT:
```rust
fn open_browser(url: &str) {
    let open_command = match env::consts::OS {
        "windows" => Command::new("cmd").args(&["/C", "start", url]),
        "macos" => Command::new("open").arg(url),
        "linux" => Command::new("xdg-open").arg(url),
        _ => {
            eprintln!("Unsupported OS");
            return;
        }
    };

    if let Err(e) = open_command.status() {
        eprintln!("Failed to open browser: {}", e);
    }
}
```

**Comment by PuruVJ** [comment]
I saw that we also pull in this crate somewhere in spacetimedb https://crates.io/crates/webbrowser, so caninstead just reuse it
