### ISSUE TITLE
Mac:  linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by marvin-hansen** [clockworklabs/SpacetimeDB#185]
Apple M1 / Ventura

XCode installed
clang version 14.0.3 (clang-1403.0.22.14.1)
rustc 1.71.1 (eb26296b5 2023-08-03)

mkdir quickstart-chat
cd quickstart-chat
spacetime init --lang rust server

cd server
cargo build 

error: linking with `cc` failed: exit status: 1
  = note: LC_ALL="C" PATH="/
......
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation

[Full log.txt](https://github.com/clockworklabs/SpacetimeDB/files/12329323/log.txt)

Apparently linking some C code together doesn't work. 

What fixed the issue for me was creating a cargo config file

vi ~/.cargo/config

and adding the following:

rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

Then cargo build finishes:

 cargo build
...
Finished dev [unoptimized + debuginfo] target(s) in 13.67

Would be great to see this kind of stuff in a troubleshooting document or FAQ.

**Comment by gefjon** [comment]
You shouldn't build Spacetime modules for non-WASM targets. The simplest way to build your module is by running `spacetime build` instead  of `cargo build`. If you want to use `cargo` directly, either pass `--target wasm32-unknown-unknown`, or use the following `.cargo/confing.toml`:

```toml
[build]
target = "wasm32-unknown-unknown"
```

We'll work on getting adding the `config.toml` to the project produced by `spacetime init`, and documenting that building modules for native targets will fail.

**Comment by marvin-hansen** [comment]
@gefjon thank you,

well, even with the target defined in a project local config.toml, I still need the workaround mentioned above to make any spacetime crate build with cargo. The problem seems to be independent of any particular target as I found[ other reports on the internet](https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1). More specifically, this seems to be a MacOS issue that hits some folks, but not others and somehow leads to the linker not being recognized automatically whenever cross-compilation happens. 

Please document this somewhere in a troubleshooting section to collect those corner cases that unavoidably pop up over time.
