### ISSUE TITLE
spacetime publish/generate --build-options requires a '=' and is undocumented

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/SpacetimeDB#1852]
This doesn't work:
```
spacetime publish --build-options'--skip-println-checks' <module-name>
```
This does work:
```
spacetime publish --build-options='--skip-println-checks' <module-name>
```

We should update the help text to make it clear that you need the `=`

**Comment by bfops** [comment]
Yeah, I mean `=` is the only way to clarify that you're passing a value to `--build-options` rather than as an arg (and `--build-options'--skip-println-checks'` is the same as `--build-options--skip-println-checks` which is.. not a valid arg).

I'll update the helptext.
