### ISSUE TITLE
wasm-bindgen will not work in the context of SpacetimeDB

### ISSUE THREAD

**Issue by marvin-hansen** [clockworklabs/SpacetimeDB#188]
Okay, this issue is about libc / bindgen.

spacetime init --lang=rs bindgen
cd bindgen
cargo add rand
spacetime build

Fixed wasm build error with [adding getrandom to cargo.toml, as stated in the manual.](https://github.com/rust-random/rand#wasm-support)

getrandom = { version = "0.2", features = ["js"] }

Added the following to lib. rs. 

```rust
use spacetimedb::{spacetimedb, ReducerContext, println};
use rand::Rng; // 0.8.5

#[spacetimedb(init)]
pub fn init() {
    let num = rand::thread_rng().gen_range(0..100);
    println!("{}", num);
}
```

spacetime build
```
Error: wasm-bindgen detected.

It seems like either you or a crate in your dependency tree is depending on
wasm-bindgen. wasm-bindgen is only for webassembly modules that target the web
platform, and will not work in the context of SpacetimeDB.

To find the offending dependency, run `cargo tree -i wasm-bindgen`. Try checking
its cargo features for 'js' or 'web' or 'wasm-bindgen' to see if there's a way
to disable it.
```

In a nutshell, rand requires libc, which is supposed to be handled by wasm-bindgen, which is not allowed in SpaceTimeDB.
That also categorically rules out most if not all crypto crates since they rely on libc for random number generation. 

Conventionally when I work with a normal DB, I have to encrypt some user data for legal compliance reasons. As I understand it now, I cannot do that with the wasm modules meaning I would have to generate client bindings, encrypt elsewhere, and do basically the exact same as I would do with a normal relational DB. 

Questions:
* Are there any plans to support libc / wasm-bindgen at any point?
* A lot of this has been fixed in wasm32-wasi, so is that an avenue you have considered?
* AFAIK, [ no_std crypto is still out of reach,](https://github.com/DaGenix/rust-crypto/issues/405) so how do I encrypt my data in SpaceTimeDB? 
* Is there any particular reason the libc / bindgen issue isn't mentioned in the docs?

The guys at ICP had almost an identical issue with their WASM runtime for canisters, but eventually provided encryption through the API with some weirdo keyless algorithm. Meaning, it can be solved, but none of the options is particular easy.

I understand it's early days and much of these issues result from the rather mixed WASM implementation in Rust (WASM-unknown vs WASM-wasi), but some guidance on the libc issue would be very much appreciated since the absence of cryptography has a very meaningful impact on application architecture.

**Comment by Jlabarca** [comment]
so how did you use rand?

**Comment by marvin-hansen** [comment]
@Jlabarca I don't. I never adopted SpaceTimeDB over this libC issue and an even [more problematic license issue. ](https://github.com/clockworklabs/SpacetimeDB/issues/215)

**Comment by gefjon** [comment]
> so how did you use rand?

@Jlabarca you can use the `getrandom` feature of the module-side `spacetimedb` crate, as demonstrated in [Part 2 of the Unity tutorial](https://spacetimedb.com/docs/unity%20tutorial/part%202%20-%20resources%20and%20scheduling)
