### ISSUE TITLE
Question about scaling

### ISSUE THREAD

**Issue by mazdak-dev** [clockworklabs/SpacetimeDB#189]
Hello, a quick question: how does this scale on multiple nodes? is there a cluster mode? I couldn't find any info on that.

**Comment by drogus** [comment]
The free version is limited to one node only (which is also a part of the BSL license). We are also working on a cloud version as @marvin-hansen mentioned and we actually have an alpha version of the cloud available: https://spacetimedb.com/docs/spacetimedb-cloud. I can't really say where will the cloud or multi-node offering end up, but for now there are no plans to release multi-node setup to the public version. All that said, the BSL license will convert to AGPL v3.0 with a linking exception, here is a paragraph from the README:

> SpacetimeDB is licensed under the BSL 1.1 license. This is not an open source or free software license, however, it converts to the AGPL v3.0 license with a linking exception after a few years.

> Note that the AGPL v3.0 does not typically include a linking exception. We have added a custom linking exception to the AGPL license for SpacetimeDB. Our motivation for choosing a free software license is to ensure that contributions made to SpacetimeDB are propagated back to the community. We are expressly not interested in forcing users of SpacetimeDB to open source their own code if they link with SpacetimeDB, so we needed to include a linking exception.

**Comment by drogus** [comment]
I'm closing the issue for now, but feel free to open [a discussion](https://github.com/clockworklabs/SpacetimeDB/discussions) if you want to discuss further, thanks!

**Comment by kenenisa** [comment]
Wanted to checkin since this discussion happened a while ago, Is it still the case that distributed deployment is not supported?
