### ISSUE TITLE
`RawModuleDef` should include fewer names, allowing the host to generate names consistently

### ISSUE THREAD

**Issue by kazimuth** [clockworklabs/SpacetimeDB#1893]
With phoebe's addition of `accessor_name` for indexes, the `name` field in various RawModuleDefs become redundant. Currently, the module bindings are allowed to specify names for `RawIndexDef` / `RawConstraintDef` / `RawScheduleDef`. These names are (almost?) completely auto-generated. The user-specified name for indexes is already its own field, `accessor_name`, distinct from these.

The problem right now is that we have to re-implement name generation in both the C# and Rust module bindings. It's a pain to make these consistent. It's much easier to just not bother, and then have the host generate all names uniformly during `RawModuleDef` validation. Names are almost entirely an internal implementation detail anyway.

**Comment by bfops** [comment]
Closed because it is marked done
