### ISSUE TITLE
Eliminate special casing of `Identity` and `Address` in SATS and codegen

### ISSUE THREAD

**Issue by bfops** [clockworklabs/SpacetimeDB#1937]
Protobufectomy makes this unnecessary; see how it handles e.g. `Timestamp` as a normal type.

**Comment by cloutiertyler** [comment]
I'm closing this one. The reasoning is that @kazimuth refactored a lot of the code gen internals so as to treat the names of types as purely code generation information and not information that should be included in the SATS types. The builtin way to add more special types like these is to include them in `TypespaceForGenerate` which a typespace that include additional metadata for generating types in a nominal type system language.

**Comment by gefjon** [comment]
We've actually gone the other way, and made more types special; it turns out to be necessary in order to correlate types referenced by multiple modules (or by both a module and the client API).
