### ISSUE TITLE
C++ Version

### ISSUE THREAD

**Issue by heapwolf** [clockworklabs/SpacetimeDB#196]
We would like to experiment with running this in the [socket runtime](https://github.com/socketsupply/socket). I realize there is a wasm version but im interested in the high performance version of this, is there a C++ port somewhere already started?

**Comment by drogus** [comment]
@heapwolf thanks for the question, although we do not plan porting anything to C++ at the moment. We are considering support for WASM modules written in C++, but it's too early to tell when it might happen

**Comment by heapwolf** [comment]
ah ok no worries, I was mislead by your readme

![image](https://github.com/clockworklabs/SpacetimeDB/assets/136109/2125ec04-e083-4ae2-a967-e1a50c4d22df)
