### ISSUE TITLE
Typescript codegen issue with csharp module.

### ISSUE THREAD

**Issue by bfops** [clockworklabs/SpacetimeDB#1977]
Generating TypeScript bindings for a module which uses a timer table fails with `error: not yet implemented`, [apparently here](https://github.com/clockworklabs/SpacetimeDB/blob/master/crates/cli/src/subcommands/generate/typescript.rs#L46), apparently while generating the bindings for the `ScheduleAt` enum. Fix this so that it's possible to generate TypeScript bindings for a module which defines at least one timer table.

Update:
Csharp module with timer fails to generate bindings for ` ScheduleAt` enum. 
Binding generated for timer struct looks like -
```
#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct SendMessageTimer {
	pub text: String,
	pub scheduled_id: u64,
	pub scheduled_at: enum { Time: u64, Interval: u64 },
}
```

May be related to Typespace not using `AlgebraicTypeRef` for `ScheduledAt` enum

```
Typespace { types: [Product(ProductType { elements: [ProductTypeElement { name: Some("Text"), algebraic_type: Builtin(String) }, ProductTypeElement { name: Some("ScheduledId"), algebraic_type: Builtin(U64) }, ProductTypeElement { name: Some("ScheduledAt"), algebraic_type: Sum(SumType { variants: [SumTypeVariant { name: Some("Time"), algebraic_type: Builtin(U64) }, SumTypeVariant { name: Some("Interval"), algebraic_type: Builtin(U64) }}] },
```

**Comment by bfops** [comment]
Did we fix this?

**Comment by bfops** [comment]
apparently it's this PR https://github.com/clockworklabs/SpacetimeDB/pull/2007

**Comment by gefjon** [comment]
Closing in favor of the linked PR, as I don't like having multiple tickets for the same work item.
