### ISSUE TITLE
CLI - Print when using an unstable command

### ISSUE THREAD

**Issue by bfops** [clockworklabs/SpacetimeDB#2004]

**Comment by gefjon** [comment]
Should likely also add unstable markers to the `--help` text of the unstable commands.

**Comment by bfops** [comment]
ah I found the other ticket I made for this: https://github.com/clockworklabs/SpacetimeDB/issues/1820

**Comment by bfops** [comment]
Closing in favor of https://github.com/clockworklabs/SpacetimeDB/issues/1820
