### ISSUE TITLE
Deploy distributed

### ISSUE THREAD

**Issue by amar-yaozhian** [clockworklabs/SpacetimeDB#205]
How to deploy distributed  SpacetimeDB on the server side.

**Comment by amar-yaozhian** [comment]
sorry not a issue

**Comment by marvin-hansen** [comment]
@amar-yaozhian In Short, you cannot. 

This has been answered in another ticket that has been closed. 

https://github.com/clockworklabs/SpacetimeDB/issues/189

**Comment by amar-yaozhian** [comment]
OK,thinks
