### ISSUE TITLE
Error configuring CLI to use SpacetimeDB Cloud while following the docs

### ISSUE THREAD

**Issue by OmegaJak** [clockworklabs/SpacetimeDB#217]
Using the SpacetimeDB CLI v0.6.1 on Windows, following https://spacetimedb.com/docs/spacetimedb-cloud.

It instructs the user to execute
```
spacetime server set 'https://testnet.spacetimedb.com'
```

but this returns `Error: Invalid protocol: 'https`

The user needs to execute it without the quotes for it to work:
```
spacetime server set https://testnet.spacetimedb.com
```

**Comment by jdetter** [comment]
@OmegaJak Was this in powershell? What OS are you on?

**Comment by OmegaJak** [comment]
I'm running Windows 10 Pro, OS build 19045.3324. This was using command prompt, not powershell. It appears to work in powershell. It appears to work in both CLIs without the quotes.
