### ISSUE TITLE
Multithreaded subscription evaluation

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#261]
All queries for a particular subscription are evaluated within a single thread of execution. An orders of magnitude speedup can be achieved using a multithreaded execution model. Not this will require some refactoring of the datastore as currently a query acquires a global exclusive lock in order to run.

**Comment by cloutiertyler** [comment]
@jdetter Please determine the prio (1 or 2) for the 0.9 release

**Comment by Shubham8287** [comment]
This has been fixed #741
