### ISSUE TITLE
Failed to get table with name: User

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#302]
<img width="1011" alt="image" src="https://github.com/clockworklabs/SpacetimeDB/assets/6432361/8cd71051-767c-4fc5-acd9-e89dcbdceb72">

**Comment by kim** [comment]
Was this reported against testnet or standalone?

**Comment by cloutiertyler** [comment]
It was confirmed that this issue occurs when trying to publish a module with an `Identity` that doesn't have enough energy. It should be fixed by:

https://github.com/clockworklabs/SpacetimeDB/pull/904

Please reopen if this issue reoccurs.
