### ISSUE TITLE
Add useful body text to error responses from `/database/publish` route

### ISSUE THREAD

**Issue by gefjon** [clockworklabs/SpacetimeDB#315]
At some point (probably introducing cloud-next), we merged a regression in the HTTP API's error reporting, where now any errors in `/database/publish` will return a 500 with no body text. The CLI uses the response body text to print its error, so we get such gems as:

```
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
   Compiling bitcraft-spacetimedb v0.1.0 (C:\ClockworkLabs\BitCraft\packages\game)
    Finished release [optimized] target(s) in 1m 02s
checking crate with spacetimedb's clippy configuration
   Compiling bitcraft-spacetimedb v0.1.0 (C:\ClockworkLabs\BitCraft\packages\game)
    Finished dev [unoptimized + debuginfo] target(s) in 19.43s
Error:
```

I also notice that we return `BAD_REQUEST` for invalid credentials, rather than `UNAUTHORIZED`.

For at least the `/database/publish` route, and ideally the entire HTTP API surface:

- [ ] Replace `auth_or_bad_request` with `auth_or_unauth`.
- [ ] Replace `log_and_500` with specific error response tuples of `(STATUS_CODE, "Message")`, where `STATUS_CODE` is an appropriate HTTP error code, and `"Message"` is a string describing what went wrong. The CLI will show that string to users on failure.

**Comment by kim** [comment]
Is this just due to bad merges?

**Comment by gefjon** [comment]
Closed by Kim's linked PR and https://github.com/clockworklabs/SpacetimeDB/pull/338 .
