### ISSUE TITLE
Skip install if cargo binaries recovered from cache on CI

### ISSUE THREAD

**Issue by RReverser** [clockworklabs/SpacetimeDB#402]
See https://github.com/clockworklabs/SpacetimeDB/actions/runs/6472740872/job/17573981627 - when `critcmp` is recovered from Github cache, `cargo install` fails because it's already installed.

**Comment by kazimuth** [comment]
Oddly, in other cases it works fine.
See e.g.
https://github.com/clockworklabs/SpacetimeDB/actions/runs/6472521530/job/17573352806#step:10:13

**Comment by RReverser** [comment]
> Oddly, in other cases it works fine.

It probably has to do whether cache was picked up or not? (e.g. if it expired)

**Comment by kazimuth** [comment]
The run I linked says `Ignored package `critcmp v0.1.8` is already installed, use --force to override` which makes me think it's there? It's the same toolchain version and machine too :(

**Comment by RReverser** [comment]
Ah no I see what you mean. It was recovered in that case.

Ah I think I know what it is - probably there is a newer version of critcmp now _and then_ I think Cargo considers it a conflict?

**Comment by RReverser** [comment]
Hm no there is no 0.1.9; super weird...

**Comment by RReverser** [comment]
Some useful info in comments here https://www.reddit.com/r/learnrust/comments/lexewr/the_difference_in_behaviour_when_running_cargo/

> My guess: an installed binary does not necessarily contain the metadata about the crate, which means that cargo needs to store versions of installed crates separately. I can see ~/.cargo/.crates.toml and ~/.cargo/.crates2.json on my machine which seem to contain this info. Maybe you are not caching these? The error also makes sense - cargo tried to install it (because it did not know that it was already installed), but failed to overwrite the executable which already exists there.

**Comment by RReverser** [comment]
Still not sure why it would work sometimes then, but looks like we don't cache that file indeed:

https://github.com/clockworklabs/SpacetimeDB/blob/ad366a740b16bced3abc8f78999c942a60ac3e57/.github/workflows/benchmarks.yml#L54-L59

**Comment by RReverser** [comment]
More generally, it might be better to switch to the dedicated rust-cache action used by other projects: https://github.com/Swatinem/rust-cache

I believe it would be more tested / reliable than whatever custom config we come up with.

**Comment by kazimuth** [comment]
Yeah. I'm tempted to just modify benchmarks.yml today and then switch to that in the future.

**Comment by kazimuth** [comment]
Also we're throwing out critcmp in #357 which should help

**Comment by RReverser** [comment]
Yeah I'd be happy with whatever temporary fix too; for now I just want to run it on my branches / PRs, but can't due to the error above.

**Comment by RReverser** [comment]
I think this was fixed.
