### ISSUE TITLE
Build a “tx / s” benchmark

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#601]
George Kulakowski comments:
This shouldn’t be too trivial (ie not inserting a single int into an empty table) but also not quite as big as some of the bitcraft reducers can get. Rather, the goal is to have a plausible number that we could have as like the “sticker price” of the db: we do up to NNN tx / s.

cc @Tyler Cloutier 

In particular, this also needs to go across the wasm boundary.

Edit pgoldman:
https://github.com/clockworklabs/SpacetimeDB/pull/345 adds tx/s measurement for the benchmarks added by https://github.com/clockworklabs/SpacetimeDB/pull/289 .

**Comment by kazimuth** [comment]
`stdb_module/disk/update_bulk/person/unique/load=1000/count=100`

On my machine, we are currently at 1000 tx/s :)
