### ISSUE TITLE
Fix disabled smoketests

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#630]
As of https://github.com/clockworklabs/SpacetimeDB/pull/629, the following smoke tests have been disabled due to flakiness
```
zz_docker-restart-module
zz_docker-restart-repeating-reducer
zz_docker-restart-sql
```
Each one involves restarting docker and therefore SpacetimeDB as well. Note that the `restart_docker` utility invokes `sleep` as a way of ensuring the necessary database components are ready. This should be replaced with a more principled way of determining when SpacetimeDB is "up".

**Comment by kim** [comment]
So this is still not fixed: some of the time, the container doesn't come up again after a restart. It is not clear what is going on from the log output, and it is of course not reproducible locally.
