### ISSUE TITLE
Track energy for disk usage

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#665]
A database's disk usage comes from 3 places - the write ahead log, large object storage (temporarily), and the [DatabaseLogger](https://github.com/clockworklabs/SpacetimeDB/blob/365b4b355ea7195a974701c4883bef650e5d498e/crates/core/src/database_logger.rs#L10). Any time bytes are added to any of the above, we need to update the database's energy usage.

By definition `1eV` is the amount of energy required to store 1 byte on disk for 1 second. Therefore if the WAL is of size `N` bytes before we write `M` bytes at time `t`, and then we write some more bytes at time `t+5s`, the amount of energy consumed by the WAL from time `t` to `t+5s` is `(N+M) * 5 eV`.

Note that we could incrementally update disk energy usage using the above formula, however this means that we need a transaction in order to trigger the update. However a database could be idle, in which case energy is still being consumed by the disk, but there are no transactions to record it. To avoid this issue we should record disk energy usage periodically like every 5s.

Note this will require that we pass an `EnergyMonitor` to a `RelationalDB` instance.

Also as part of this ticket, we should mirror these energy metrics in prometheus.

**Comment by cloutiertyler** [comment]
Technically we don't guarantee that we will persist the `DatabaseLogger` logs, so we could leave that one out.

**Comment by joshua-spacetime** [comment]
We can certainly remove it then, but even if we don't guarantee it's persistence, if we do indeed persist the `DatabaseLogger` logs, then I think we should track it.
