### ISSUE TITLE
Track energy for persistent database memory

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#667]
We should track the persistent memory associated with tables and indexes for energy purposes. This means each table and index needs access to an `EnergyMonitor` for recording energy use.

If `1 eV` is the amount of energy used to store 1 byte on disk for 1 second, then `N eV` is the amount of energy required to store 1 byte in memory for 1 second for some `N`. We should pick a suitable `N` and record, for every insert/delete, the amount of energy used per table, since the previous insert/delete.

As part of this ticket we should also write these energy recordings to prometheus.

**Comment by cloutiertyler** [comment]
1000 is not so far from a suitable N (for context)

**Comment by cloutiertyler** [comment]
We would like to see the number of bytes per table so that we can track which tables have very large rows.

**Comment by gefjon** [comment]
> We would like to see the number of bytes per table so that we can track which tables have very large rows.

It would be very easy to compute a conservative overestimate of this by simply tracking the number of pages per table in the committed state. A precise count is more challenging.

**Comment by cloutiertyler** [comment]
I split this ticket into https://github.com/orgs/clockworklabs/projects/22/views/38?pane=issue&itemId=47389802 as well
