### ISSUE TITLE
Stop telling people to "delete their .spacetime folder" and instead add a `.spacetime/data` directory which can be cleared instead

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/SpacetimeDB#670]
Maybe we add the following commands:

 `spacetime local clear --all --force`
 `spacetime local clear bitcraft --force`

or something similar.

NOTE! These commands should not act through an API, but instead should just remove the appropriate data in the data directory. i.e. you have permission to delete the data if and only if you could `rm -rf` the folder.

**Comment by jdetter** [comment]
https://github.com/clockworklabs/SpacetimeDB/pull/699

**Comment by jdetter** [comment]
https://github.com/clockworklabs/SpacetimeDB/pull/702
