### ISSUE TITLE
"Builtin reducer" callbacks

### ISSUE THREAD

**Issue by kim** [clockworklabs/SpacetimeDB#671]
The generated Rust code dispatching reducer events currently does not know about "builtin" reducer names such as `__identity_connected__`, and emits a log line at ERROR level when it encounters it.

It is unclear if it should not receive those events in the first place, ignore them, or dispatch them to some callback function.

jdetter note: I created a ticket for this in the C# SDK: https://github.com/clockworklabs/spacetimedb-csharp-sdk/issues/102

**Comment by gefjon** [comment]
Likely we should have a callback `on_identity_connected` or `on_identity_disconnected`, and corresponding `ReducerEvent` variants. The SDK should not generate code to invoke these reducers, only to listen for them.

Open questions:
- Should we codegen for these reducers if the module does not define them?
  - Inclination: doesn't matter, so whatever's easiest.
- Do we need to handle the extra TX for `st_clients`?
  - Inclination: no special handling.
- Should we generate the callbacks with hardcoded names, or respect the names defined by the module?
  - Unlike `#[spacetimedb(reducer)]`, `#[spacetimedb(connect)]` does not capture the source function name in the module's description.
  - Inclination: hardcoded names are fine.

**Comment by gefjon** [comment]
Moving ticket to "in review" as this is addressed by the API stability proposal
