### ISSUE TITLE
Batch and record metrics async

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#726]
All metrics are recorded synchronously at the moment. Concretely what this means is that the prometheus client that is used to record the metrics for a transaction is called within the same transaction. And potentially multiple times within a transaction. This can have a meaningful impact on latencies since `with_label_values` is a relatively expensive call. Instead we should batch/aggregate metrics and call `with_label_values` asynchronously.

**Comment by Shubham8287** [comment]
@joshua-spacetime, Can you close this if it has been fixed now?
