### ISSUE TITLE
Add methods to Timestamp for deriving month and year

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#753]
The Timestamp type in the bindings module should have methods `month()` and `year()`. Note this means adding a dependency on the `chrono` library in all likelihood.

**Comment by cloutiertyler** [comment]
Having spoken with @joshua-spacetime, we're going to just close this one for now and open it again later if necessary. We're concerned about adding a new dependency to the `spacetimedb-lib` crate for unclear purposes before stability.
