### ISSUE TITLE
Stop cloning Headers in query evaluation

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#834]
In relation to queries, table headers are static and should not need to be cloned. The cloning of table headers represents a significant portion of query execution time as they are attached to query plans and even result sets. ~~We should remove the `Clone` derivation from `Header` in favor of explicit instantiation.~~ And in most cases within the query layer, headers should only ever be read and not instantiated.

**Comment by gefjon** [comment]
Everywhere a header is used and cloned, wrap it in `Arc`. Remember to add comment that we should compile headers down to... something better? Indexes rather than field names?

**Comment by joshua-spacetime** [comment]
> Indexes rather than field names?

Yes.

Arc should be good enough for now. We can remove it when we implement the proper solution that you suggested.
