### ISSUE TITLE
Make field lookups in Header faster

### ISSUE THREAD

**Issue by joshua-spacetime** [clockworklabs/SpacetimeDB#932]
![Image](https://github.com/clockworklabs/SpacetimeDB/assets/141075564/37a61362-9eeb-4d80-a86d-e3fb0290ddb1)

This is a profile from a recent benchmark run for incremental select. The red is `Header::find_pos_by_name` which represents ~30% of eval_incr. This this function were just a lookup into a hash map, we could effectively remove this from the profile.

**Comment by mamcx** [comment]
This was aborted
